# Generated by Django 4.2.11 on 2026-09-12 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Путь')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='Метод')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время посещения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='analytics_p_visited_49d70d_idx'), models.Index(fields=['path', '-visited_at'], name='analytics_p_path_1c8240_idx')],
            },
        ),
    ]
